# Makefile for running each node

1:
	python3 myleprocess.py x 1

2:
	python3 myleprocess.py n 2

3:
	python3 myleprocess.py n 3

4:
	python3 myleprocess.py n 4

5:
	python3 myleprocess.py y 5
