# Makefile for running each node

# Generic run command - still need to specify <node_type> and <config_id>
run:
	python3 myleprocess.py

# Preset node types according to example topology
test1:
	python3 myleprocess.py x 1

test2:
	python3 myleprocess.py n 2

test3:
	python3 myleprocess.py n 3

test4:
	python3 myleprocess.py n 4

test5:
	python3 myleprocess.py y 5
